% save the gradient generated by example_yjs_1H.m
filename = 'C:\Users\P53-LOCAL\Desktop\AI\compressed_sensing\codes\spiral_TO.txt';

g_riv = g_riv * 10; % G/cm -> mT/m (scanner);

gx = g_riv(:,1);
gy = g_riv(:,2);

gx_scale = max(max(gx), abs(min(gx))); % max(abs(g))
gy_scale = max(max(gy), abs(min(gy))); % max(abs(g))

N = length(g_riv);

fid = fopen(filename, 'wt');
if fid ~= -1
    fprintf(fid, 'Gradient waveform for time-optimal spiral\n');
    fprintf(fid, '%d\n', N);
    fprintf(fid, '%f\n', gx_scale);
    fprintf(fid, '%f\n', gy_scale);

    for idx=1:N
        fprintf(fid, '%f\n', gx(idx)/gx_scale);
    end
    
    fprintf(fid,'\n');

    for idx=1:N
        fprintf(fid, '%f\n', gy(idx)/gy_scale);
    end

    fclose(fid);
else
    warningMessage = sprintf('Cannot open file %s', filename);
    uiwait(warndlg(warningMessage));
end
